#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# ä¸€æ¬¡åªèƒ½ç¼–è¯‘ä¸€ä¸ª

name: OpenWrtç¼–è¯‘(æ‰‹åŠ¨æŒ‡å®šç‰ˆæœ¬)

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'é€‰æ‹©ç‰ˆæœ¬'
        required: true
        default: 'openwrt_24.10.0'
#  repository_dispatch:

env:
  GITHUB_LINK: https://github.com/${{github.repository}}
  GIT_REPOSITORY: ${{github.repository}}
  UPLOAD_BIN_DIR: true                         #ä¸Šä¼  bin ç›®å½•ã€‚å³åŒ…å«æ‰€æœ‰ ipk æ–‡ä»¶å’Œå›ºä»¶çš„ç›®å½•ã€‚é»˜è®¤false
  UPLOAD_FIRMWARE: true                         #ä¸Šä¼ å›ºä»¶ç›®å½•ã€‚é»˜è®¤true
  UPLOAD_RELEASE: true                         #ä¸Šä¼ å›ºä»¶åˆ° releases ã€‚é»˜è®¤false
  UPLOAD_TRANSFER: false                        #å¥¶ç‰›å¿«ä¼ å’Œwetransferå¿«ä¼ 

  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    #èµ‹äºˆå†™å…¥æƒé™
 #   permissions:
 #     contents: write
      
    #é€‰æ‹©ç³»ç»Ÿç‰ˆæœ¬
    name: ç¼–è¯‘${{github.event.inputs.target}}
    strategy:
      fail-fast: true                      # trueï¼šåªè¦æµç¨‹ä¸­æœ‰å¤±è´¥ï¼Œè‡ªåŠ¨åœæ­¢æ‰€æœ‰æµç¨‹

    steps:
    - name: æ‹‰å–ä»“åº“
      uses: actions/checkout@main

    - name: æ¸…ç†ç£ç›˜ç©ºé—´
      uses: jlumbroso/free-disk-space@main
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true       # å¦‚æœä½ ä¸ä½¿ç”¨ Dockerï¼Œå¯ä»¥è®¾ä¸º true
        swap-storage: true
        tool-cache: false          # ä¿ç•™å·¥å…·ç¼“å­˜ï¼Œé¿å…è¯¯åˆ  Python3 ç­‰

    - name: æŸ¥çœ‹ç£ç›˜ç©ºé—´
      run: |
        echo "å½“å‰ç£ç›˜ç©ºé—´ï¼š"
        df -h

    # - name: æ¸…ç†ç£ç›˜ç©ºé—´
    #   run: |
    #     echo "ğŸ§¹ å¼€å§‹æ¸…ç†ç£ç›˜ç©ºé—´..."
    #     sudo rm -rf /usr/share/dotnet
    #     sudo rm -rf /usr/local/lib/android
    #     sudo rm -rf /opt/ghc
    #     sudo rm -rf /opt/hostedtoolcache/CodeQL
    #     sudo rm -rf /opt/microsoft
    #     sudo rm -rf /opt/pipx
    #     sudo rm -rf /usr/share/swift
    #     sudo apt-get clean
    #     sudo apt-get autoremove -y
    #     echo "âœ… æ¸…ç†å®Œæˆï¼Œå½“å‰ç£ç›˜ç©ºé—´ï¼š"
    #     df -h

    - name: é…ç½®gitç¯å¢ƒï¼Œä½¿ç”¨è‡ªå·±çš„token(ç§æœ‰ä»“åº“æ—¶ä½¿ç”¨)
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://pencail:${{ secrets.TOKEN_PENCAIL }}@github.com/

    - name: æ£€æµ‹è„šæœ¬è®¾ç½®
      run: |
        source "${GITHUB_WORKSPACE}/build/${{github.event.inputs.target}}/settings.ini"

        echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
        echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
        echo "CONFIG_FILE=${CONFIG_FILE}" >> ${GITHUB_ENV}
        echo "FEEDS_CONF=${FEEDS_CONF}" >> ${GITHUB_ENV}
        echo "DIY_P1_SH=${DIY_P1_SH}" >> ${GITHUB_ENV}
        echo "DIY_P2_SH=${DIY_P2_SH}" >> ${GITHUB_ENV}

    # - name: éƒ¨ç½²ç¼–è¯‘ç¯å¢ƒ
    #   env:
    #     DEBIAN_FRONTEND: noninteractive
    #   run: |
    #     sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    #     sudo -E apt-get -qq update
    #     sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
    #     sudo -E apt-get -qq autoremove --purge
    #     sudo -E apt-get -qq clean
    #     sudo timedatectl set-timezone "$TZ"
    #     sudo mkdir -p /workdir
    #     sudo chown $USER:$GROUPS /workdir

    - name: éƒ¨ç½²ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: ä¸‹è½½å›ºä»¶
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: åŠ è½½è‡ªå®šä¹‰æº(feeds)ï¼ŒåŒæ—¶è¿è¡Œpart1è„šæœ¬
      run: |
        if [ -f "build/${{github.event.inputs.target}}/$FEEDS_CONF" ]; then
          cp build/${{github.event.inputs.target}}/$FEEDS_CONF openwrt/feeds.conf.default
        fi
        
        chmod +x build/${{github.event.inputs.target}}/$DIY_P1_SH
        cd openwrt
        /bin/bash "$GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/$DIY_P1_SH"
#        [ -e $FEEDS_CONF ] && 

    - name: æ›´æ–°è‡ªå®šä¹‰æº(feeds)
      run: cd openwrt && ./scripts/feeds update -a
    
    - name: åˆ é™¤è‡ªå®šä¹‰æºä¸­çš„argon
      working-directory: openwrt
      run: |
        rm -rf feeds/pencail/luci-theme-argon
        rm -rf feeds/pencail/luci-app-argon-config
#        rm -rf feeds/kenzo/luci-theme-argon
#        rm -rf feeds/kenzo/luci-them-argone
#        rm -rf feeds/kenzo/luci-app-argone-config
    
    - name: å®‰è£…è‡ªå®šä¹‰æº(feeds)
      run: cd openwrt && ./scripts/feeds install -a
      

    - name: åŠ è½½é…ç½®æ–‡ä»¶(config)ï¼ŒåŒæ—¶è¿è¡Œpart2è„šæœ¬
      run: |
        cp build/${{github.event.inputs.target}}/$CONFIG_FILE openwrt/.config
        chmod +x build/${{github.event.inputs.target}}/$DIY_P2_SH    
        cd openwrt
        /bin/bash "$GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/$DIY_P2_SH"
#        [ -e $CONFIG_FILE ] && 
        
    - name: åŠ è½½fileæ–‡ä»¶
      run: |
        if [ -n "$(ls -A "build/${{github.event.inputs.target}}/DIY" 2>/dev/null)" ]; then
          cp -Rf $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/DIY/* openwrt
        fi

    - name: åŠ è½½å†…æ ¸MD5æ–‡ä»¶
      run: |
        if [ -n "$(ls -A "build/${{github.event.inputs.target}}/md5.vermagic" 2>/dev/null)" ]; then
          cp -Rf $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/md5.vermagic openwrt/.vermagic
        fi

    - name: ä¸‹è½½è½¯ä»¶åŒ…
      working-directory: openwrt
      id: package
      run: |
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    - name: åŠ è½½è¡¥ä¸æ–‡ä»¶
      working-directory: openwrt
      run: |
        if [ -n "$(ls -A "$GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/patches" 2>/dev/null)" ]; then
          chmod +x $GITHUB_WORKSPACE/scripts/apply_all_patches.sh
          cp -Rf $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/patches patches
          echo "ğŸ§© æ­£åœ¨åº”ç”¨è¡¥ä¸æ–‡ä»¶..."  
          /bin/bash $GITHUB_WORKSPACE/scripts/apply_all_patches.sh patches $GITHUB_WORKSPACE/build/${{github.event.inputs.target}}/patchmap.yml logs/patchlog.txt

          echo "ğŸ§© è¡¥ä¸æ—¥å¿—é¢„è§ˆï¼š"
          tail -n 10 logs/patchlog.txt || echo "(âš ï¸ æ— æ—¥å¿—è¾“å‡º)"
        fi

    - name: ä¸Šä¼ è¡¥ä¸æ—¥å¿—
      uses: actions/upload-artifact@main
      if: success()
      with:
        name: patchlog
        path: openwrt/logs/patchlog.txt

    - name: å¼€å§‹ç¼–è¯‘
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d-%H.%M")" >> $GITHUB_ENV

    - name: æ£€æŸ¥ç©ºé—´ä½¿ç”¨æƒ…å†µ
      if: (!cancelled())
      run: df -hT

    - name: ä¸Šä¼ binæ–‡ä»¶å¤¹(å›ºä»¶+ipk)åœ¨githubç©ºé—´
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: æ•´ç†å›ºä»¶æ–‡ä»¶å¤¹
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ä¸Šä¼ å›ºä»¶åœ¨githubç©ºé—´
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

#    - name: ç”Ÿæˆtag
#      id: tag
#      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
#      run: |
#        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
#        touch release.txt
#        [ $UPLOAD_COWTRANSFER = true ] && echo "ğŸ”— [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
#        [ $UPLOAD_WETRANSFER = true ] && echo "ğŸ”— [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
#        echo "status=success" >> $GITHUB_OUTPUT

#    - name: è‡ªåŠ¨å‘å¸ƒå›ºä»¶
#      uses: softprops/action-gh-release@v1
#      if: steps.tag.outputs.status == 'success' && !cancelled()
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ steps.tag.outputs.release_tag }}
#        body_path: release.txt
#        files: ${{ env.FIRMWARE }}/*

    - name: ä¸Šä¼ å›ºä»¶åˆ°ã€Œå¥¶ç‰›å¿«ä¼ ã€å’Œã€Œwetransferã€
      id: transfer
      if: steps.organizer.outputs.status == 'success' && env.UPLOAD_TRANSFER == 'true' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "status=success" >> $GITHUB_OUTPUT
        
    - name: æå–å‘å¸ƒç”¨çš„ã€Œå¥¶ç‰›å¿«ä¼ ã€è·Ÿã€ŒWeTransferã€çš„é“¾æ¥
      if: steps.organizer.outputs.status == 'success' && steps.transfer.outputs.status == 'success' && !cancelled()
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
        echo "COWTRANSFER_URL=$(cat cowtransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV 
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
        echo "WETRANSFER_URL=$(cat wetransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV

    - name: ç”Ÿæˆtag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H.%M")" >> $GITHUB_OUTPUT
        echo "status=success" >> $GITHUB_OUTPUT

    - name: è‡ªåŠ¨å‘å¸ƒå›ºä»¶
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.FILE_DATE }} ã€Œ ${{ env.REPO_BRANCH }} ã€å›ºä»¶
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body: |
            â˜†  æºç  : ${{ env.REPO_URL }}
            â˜†  åˆ†æ”¯ : ${{ env.REPO_BRANCH }}
            â˜†  æ„Ÿè°¢æºç ä½œè€…æ— ç§åˆ†äº«ï¼

#            ğŸ‰ [ ${{matrix.target}} ]å›ºä»¶ä¸‹è½½ âœ¨
            
#            ğŸ’ å¥¶ç‰›å¿«ä¼ (å›½å†…é«˜é€ŸğŸš€ä¸‹è½½)ï¼š ${{ env.COWTRANSFER_URL }}
            
#            â›„ WeTransfer(å›½å¤–é«˜é€ŸğŸš€ä¸‹è½½)ï¼š ${{ env.WETRANSFER_URL }}
            
#            ğŸŒ´ é“¾æ¥æœ‰æ•ˆæœŸä¸º7å¤©ï¼Œæ— éœ€æ³¨å†Œç›´æ¥ä¸‹è½½ ğŸ¤
        files: ${{ env.FIRMWARE }}/*

    - name: telegramé€šçŸ¥(ç¼–è¯‘æˆåŠŸ)
      uses: appleboy/telegram-action@master
      if: steps.organize.outputs.status == 'success'
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        message: |
           ã€Œ ${{ env.REPO_BRANCH }} ã€å›ºä»¶ç¼–è¯‘æˆåŠŸ
           è¯·å‰å¾€æŸ¥çœ‹ https://github.com/${{ github.repository }}/releases
           æ—¶é—´ï¼š${{ steps.tag.outputs.release_tag }}

    - name: telegramé€šçŸ¥(ç¼–è¯‘å¤±è´¥)
      uses: appleboy/telegram-action@master
      if: steps.organize.outputs.status != 'success'
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_TOKEN}}
        message: |
           ã€Œ ${{ env.REPO_BRANCH }} ã€å›ºä»¶ç¼–è¯‘å¤±è´¥
           è¯·å‰å¾€æŸ¥çœ‹ https://github.com/${{ github.repository }}/action
           ç¼–è¯‘æ—¶é—´ï¼š${{ env.FILE_DATE }}

    - name: åˆ é™¤å·¥ä½œæµ
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: åˆ é™¤æ—§çš„Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
